### ISSUE TITLE
`refine .` should work

### ISSUE THREAD

**Issue by TheTechRobo** [rsalmei/refine#1]
You should be able to run `refine .` for the current working directory, `..`, etc. Right now I get:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/thetechrobo/.cargo/registry/src/github.com-1ecc6299db9ec823/refine-0.2.2/src/main.rs:11:12
```

**Comment by rsalmei** [comment]
Hi @TheTechRobo!

Thanks, it is fixed on the current version! And there's a new command: rebuild.
