### ISSUE TITLE
Gracefully handle Ctrl-C

### ISSUE THREAD

**Issue by TheTechRobo** [rsalmei/refine#2]
It'd be nice if refine would stop searching and show the current list of duplicates if you press Ctrl-C instead of just aborting.

**Comment by rsalmei** [comment]
Humm, this one is interesting because it takes only a few hundred milliseconds here on my machine... I couldn't manually interrupt it because it would already have finished, even with thousands of files.

Did it take more time on your system, so you felt the need to interrupt it?

**Comment by TheTechRobo** [comment]
Running this on my home folder on my laptop takes about 29 seconds. It has an i5-8350U CPU, and `find | wc -l` returns `527363`. However, running it again (I guess once most of the data is cached in memory) only takes 4 seconds.

Granted, it's rather unlikely that people would run this on their home folder.

**Comment by rsalmei** [comment]
Hey @TheTechRobo, thanks for trying this out!
That was pretty impressive, running a duplicate finder on over 500 thousand files!!
Oh, and thanks for finding me here in this Rust realm! Currently, I'm much more involved with Rust than Python.

Anyway, were these numbers on the latest published version? If not, could you please try it again with the latest one?
The dupe finder now is much more polished than the 2022 one, and I'd like to see how it behaves with such a huge test.

**Comment by TheTechRobo** [comment]
Assuming the crates.io release was up to date, I did run it using the latest release. `refine --version` reports 0.6.0.

**Comment by rsalmei** [comment]
Great, thank you. It's that version indeed, I'm here working on the 0.7.0 one.
So, it must be running a release version. I mean, you `cargo install refine`, not `git clone ...; cargo run`, right?
Does your laptop have an SSD?

**Comment by TheTechRobo** [comment]
Yeah, it's an SSD. And yes, I did use `cargo install refine`.

**Comment by rsalmei** [comment]
I just released 0.7.0, could you please test it again?

**Comment by TheTechRobo** [comment]
Still takes about 30 seconds. Though that could just be variance in what is cached in memory.

The speed isn't so much of a problem.  But allowing Ctrl-C would be convenient for when it is necessary and when you can't improve performance any more (e.g. spinning hard drive).

**Comment by rsalmei** [comment]
Yep, I agree. Thank you.

**Comment by rsalmei** [comment]
@TheTechRobo, would you please rerun it with `--sample 0`?
That way, we can understand whether the loading of file samples or the actual dir walking is slow.

**Comment by TheTechRobo** [comment]
Seems to have been much faster, completing in a third of the time of before. Subsequent runs (when everything is cached) complete in 3-4 seconds.

**Comment by rsalmei** [comment]
Hey @TheTechRobo, it is done!
I'm publishing v0.9 with it right now.
The commit will close this issue, but please let me know if it works for you.
